namespace Bpsim.Parts
{
	public enum LegacyPartType
	{
		Unknown = 0,
		Balloon = 1,
		Balloons2 = 2,
		Balloons3 = 3,
		Fan = 4,
		WoodenFrame = 5,
		Bellows = 6,
		CartWheel = 7,
		Basket = 8,
		Sandbag = 9,
		Pig = 10,
		Sandbag2 = 11,
		Sandbag3 = 12,
		Propeller = 13,
		Wings = 14,
		Tailplane = 15,
		Engine = 16,
		Rocket = 17,
		MetalFrame = 18,
		SmallWheel = 19,
		MetalWing = 20,
		MetalTail = 21,
		Rotor = 22,
		MotorWheel = 23,
		TNT = 24,
		EngineSmall = 25,
		EngineBig = 26,
		NormalWheel = 27,
		Spring = 28,
		Umbrella = 29,
		Rope = 30,
		CokeBottle = 31,
		KingPig = 32,
		RedRocket = 33,
		SodaBottle = 34,
		PoweredUmbrella = 35,
		Egg = 36,
		JetEngine = 37,
		ObsoleteWheel = 38,
		SpringBoxingGlove = 39,
		StickyWheel = 40,
		GrapplingHook = 41,
		Pumpkin = 42,
		Kicker = 43,
		Gearbox = 44,
		GoldenPig = 45,
		PointLight = 46,
		SpotLight = 47,
		TimeBomb = 48,
		ElectricalPart = 49,
		MechanicalPart = 50,
		MAX = 51
	}
}
